apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xib074lio-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xib074lio-dotnet-basic-gitops